=== center-for-threat-informed-defense/attack-flow/schema/attack-flow-2021-11-03-draft.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mitre-engenuity.com/schema/attack-flow/2021-10-13-draft.json",
    "title": "Attack Flow",
    "description": "This schema describes the Attack Flow JSON format.",
    "type": "object",
    "properties": {
        "flow": {
            "description": "An Attack Flow Meta object",
            "type": "object",
            "properties": {
                "type": {
                    "description": "Indicate that this is an Attack Flow.",
                    "type": "string",
                    "enum": ["attack-flow"]
                },
                "id": {
                    "description": "The identifier for this Attack Flow. MUST be unique within this document. TODO: Ideally is unique among Attack Flows produced by a particular organization.",
                    "type": "string",
                    "format": "uri"
                },
                "name": {
                    "description": "The name of the Attack Flow.",
                    "type": "string"
                },
                "created": {
                    "description": "Creation time of the Attack Flow.",
                    "type": "string",
                    "format": "date-time"
                },
                "author": {
                    "description": "The author of the Attack Flow.",
                    "type": "string"
                },
                "description": {
                    "description": "The description of the Attack Flow.",
                    "type": "string"
                }
            },
            "required": [
                "type",
                "id",
                "name",
                "created"
            ]
        },
        "actions": {
            "description": "The list of action nodes in the attack flow",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "description": "The identifier for this Action. MUST be unique within this document.",
                        "type": "string",
                        "format": "uri"
                    },
                    "type": {
                        "description": "Indicate that this is an Action",
                        "type": "string",
                        "enum": ["action"]
                    },
                    "name": {
                        "description": "The name of the action. May be an ATT&CK technique name.",
                        "type": "string"
                    },
                    "description": {
                        "description": "A description of the action.",
                        "type": "string"
                    },
                    "timestamp": {
                        "description": "The timestamp when this action was observed.",
                        "type": "string",
                        "format": "date-time"
                    },
                    "reference": {
                        "description": "A reference for the action. May be a URL to an ATT&CK technique.",
                        "type": "string"
                    },
                    "succeeded": {
                        "description": "Float from 0 (failed) to 1 (succeeded) or distribution representing the probability that action succeeded in its effects. Any effects which may be separable should be defined through a separate action. Assumed to be 1 (100% ~ TRUE) if not included.",
                        "type": "number"
                    },
                    "confidence": {
                        "description": "Float from 0 to 1 or distribution representing the confidence that the action succeeded. Assumed to be 1 (100% ~ ground truth) if not included.",
                        "type": "number"
                    },
                    "logic_operator_language": {
                        "description": "The language of the logic_operator. Defaults to flow-vTBD when left blank.",
                        "type": "string"
                    },
                    "logic_operator": {
                        "description": "The logic_operator may be any logic valid in the language defined by the logic_operator_language. If the logic_operator_language is undefined, the logic_operator may be AND or OR, representing the relative operation on all required-by relationships. The logic_operator must return the state changes to the provides relationships. Inputs to the logic_operator are required-by Assets and their states; outputs of the logic_operator are provides Assets and their states updates.",
                        "type": "string",
                        "default": "AND"
                    }
                },
                "required": ["id", "name", "description", "logic_operator"]
            }
        },
        "assets": {
            "description": "The list of asset nodes in the attack flow",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "description": "The identifier for this Asset. MUST be unique within this document.",
                        "type": "string",
                        "format": "uri"
                    },
                    "type": {
                        "description": "Indicate that this is an Asset",
                        "type": "string",
                        "enum": ["asset"]
                    },
                    "state": {
                        "description": "A property that may be used as a transient string representing the state of the object during a point in time representing the current state of the system. The sum of all object states is the state of the system. This may be as simple as \"compromised\", the Confidentiality, Integrity, Availability triad, DIMFUI (Degradation, Interruption, Modification, Fabrication, Unauthorized Use, and Interception), or it may even be an arbitrary string. If not included, it is assumed that the state is 'compromised' after a parent action succeeds.",
                        "type": "string"
                    }
                },
                "required": ["id"],
                "additionalProperties": false
            }
        },
        "relationships": {
            "description": "The list of relationship edges in the attack flow. All Actions MUST have a relationship to the flow. See Relationships table for valid pairs of source and target entities.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "source": {
                        "description": "The source flow, action, or asset for this relationship.",
                        "type": "string",
                        "format": "uri"
                    },
                    "type": {
                        "description": "The type of relationship.",
                        "type": "string",
                        "format": "uri"
                    },
                    "target": {
                        "description": "The target flow, action, or asset.",
                        "type": "string"
                    }
                },
                "required": ["source", "type", "target"],
                "additionalProperties": false
            }
        },
        "data_properties": {
            "description": "Data properties associate actions, assets, properties, or flows with a piece of data.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "description": "Type (or \"name\") of property.",
                        "type": "string",
                        "format": "uri"
                    },
                    "source": {
                        "description": "The source flow, action, asset, or property for this property.",
                        "type": "string",
                        "format": "uri"
                    },
                    "target": {
                        "description": "Value for the specific type for the source object.",
                        "type": "string"
                    }
                },
                "required": ["source", "type", "target"]
            }
        },
        "object_properties": {
            "description": "Object properties relate, actions, assets, properties, or flows to other assets, properties, or flows. (Some rules apply.)",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "description": "Type (or \"name\") of property.",
                        "type": "string",
                        "format": "uri"
                    },
                    "source": {
                        "description": "The source flow, action, asset, or property for this property.",
                        "type": "string",
                        "format": "uri"
                    },
                    "target": {
                        "description": "Target flow, asset, or property for this property.",
                        "type": "string",
                        "format": "uri"
                    }
                },
                "required": ["source", "type", "target"],
                "additionalProperties": false
            }
        }

    },
    "additionalProperties": true,
    "required": [
        "flow",
        "actions",
        "assets",
        "relationships"
    ]
}

=== center-for-threat-informed-defense/attack-flow/corpus/mac_malware_steals_cryptocurrecy.json
{
    "$schema": "../schema/attack-flow-2022-01-05-draft.json",
    "flow": {
        "type": "attack-flow",
        "id": "https://unit42.paloaltonetworks.com/mac-malware-steals-cryptocurrency-exchanges-cookies/",
        "name": "Mac Malware Steals Cryptocurrency Exchanges Cookies",
        "author": "Eric Kannampuzha",
        "created": "2022-01-28T19:05:51-08:00"
    },
    "actions": [
        {
            "id": "http://flow-1/action-1",
            "type": "action",
            "name": "Command and Scripting Interpreter: Unix Shell",
            "description": "A shell script is executed to copy Safari browser's cookies and upload them to a remote service.",
            "reference": "https://attack.mitre.org/techniques/T1059/004/",
            "succeeded": 0,
            "confidence": 0,
            "logic_operator_language": "",
            "logic_operator": "AND"
        },
        {
            "id": "http://flow-1/action-2",
            "type": "action",
            "name": "Command and Scripting Interpreter: Python",
            "description": "A python script named \"harmlesslittlecode.py\" is run to extract saved login credentials and credit card information from Google Chrome.",
            "reference": "https://attack.mitre.org/techniques/T1059/006/",
            "succeeded": 0,
            "confidence": 0,
            "logic_operator_language": "",
            "logic_operator": "AND"
        },
        {
            "id": "http://flow-1/action-3",
            "type": "action",
            "name": "Resource Hijacking",
            "description": "The xmrig2 Mach-O executable is launched to mine cryptocurrency",
            "reference": "https://attack.mitre.org/techniques/T1496/",
            "succeeded": 0,
            "confidence": 0,
            "logic_operator_language": "",
            "logic_operator": "AND"
        },
        {
            "id": "http://flow-1/action-4",
            "type": "action",
            "name": "Ingress Tool Transfer",
            "description": "A base64 encoded version of the EmPyre post-exploitation Python script is downloaded.",
            "reference": "https://attack.mitre.org/techniques/T1105/",
            "succeeded": 0,
            "confidence": 0,
            "logic_operator_language": "",
            "logic_operator": "AND"
        },
        {
            "id": "http://flow-1/action-5",
            "type": "action",
            "name": "Software Discovery: Security Software Discovery",
            "description": "The EmPyre agent checks if Little Snitch is running on the victim's host.",
            "reference": "https://attack.mitre.org/techniques/T1518/001/",
            "succeeded": 0,
            "confidence": 0,
            "logic_operator_language": "",
            "logic_operator": "AND"
        }
    ],
    "assets": [
        {
            "id": "http://flow-1/asset-6",
            "type": "asset",
            "state": "Credit Card Information"
        },
        {
            "id": "http://flow-1/asset-7",
            "type": "asset",
            "state": "Credentials"
        },
        {
            "id": "http://flow-1/asset-8",
            "type": "asset",
            "state": "Cryptocurrency Wallet Private Keys"
        },
        {
            "id": "http://flow-1/asset-9",
            "type": "asset",
            "state": "SMSFILE"
        },
        {
            "id": "http://flow-1/asset-10",
            "type": "asset",
            "state": "Browser Cookies"
        },
        {
            "id": "http://flow-1/asset-11",
            "type": "asset",
            "state": "EmPyre Agent"
        },
        {
            "id": "http://flow-1/asset-12",
            "type": "asset",
            "state": "Cryptocurrency"
        }
    ],
    "relationships": [
        {
            "source": "http://flow-1/action-1",
            "type": "http://flow-1#provides",
            "target": "http://flow-1/asset-10"
        },
        {
            "source": "http://flow-1/action-2",
            "type": "http://flow-1#provides",
            "target": "http://flow-1/asset-6"
        },
        {
            "source": "http://flow-1/action-2",
            "type": "http://flow-1#provides",
            "target": "http://flow-1/asset-7"
        },
        {
            "source": "http://flow-1/action-2",
            "type": "http://flow-1#provides",
            "target": "http://flow-1/asset-8"
        },
        {
            "source": "http://flow-1/action-2",
            "type": "http://flow-1#provides",
            "target": "http://flow-1/asset-9"
        },
        {
            "source": "http://flow-1/action-4",
            "type": "http://flow-1#Provides",
            "target": "http://flow-1/asset-11"
        },
        {
            "source": "http://flow-1/asset-11",
            "type": "http://flow-1#required-by",
            "target": "http://flow-1/action-5"
        },
        {
            "source": "http://flow-1/action-3",
            "type": "http://flow-1#provides",
            "target": "http://flow-1/asset-12"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/action-1"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/action-2"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/action-3"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/action-4"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/action-5"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/asset-6"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/asset-7"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/asset-8"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/asset-9"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/asset-10"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/asset-11"
        },
        {
            "source": "http://flow-1",
            "type": "http://flow-1#flow-edge",
            "target": "http://flow-1/asset-12"
        }
    ],
    "object_properties": [],
    "data_properties": [
        {
            "source": "http://flow-1/asset-11",
            "type": "http://flow-1#state",
            "target": "Base64 Encoded"
        }
    ]
}
